### ISSUE TITLE
Does not fully support UTF-8 emojis

### ISSUE THREAD

**Issue by SpraxDev** [Hinaser/gfm-advanced#5] opened 2020-11-03 02:52 UTC
Hey! Just downloaded your plugin and realized that some UTF-8 emojis are rendered wrong. e.g. `🎨` or `🌍`

![Screenshot](https://user-images.githubusercontent.com/7331598/97945401-bdf9fe80-1d87-11eb-8463-4c4434952ac0.png)

WebStorm: 2020.2.3
GfmA: 0.0.3

**Comment by Hinaser** [comment] 2021-01-12 16:25
Sorry for late, but I confirmed this issue.
I'll see to it.

**Comment by Hinaser** [comment] 2021-01-12 17:24
## Memo
Looks like the issue is in `GetStringUTFChars()`  at JNI, which converts Java portion of `String` data to C++ portion of `char*` value.

## References
https://bitbucket.org/search?q=repo%3Ajava-cef%20executeJavascript&account=%7Bdc443723-7652-4c63-b340-033e522146db%7D
https://bitbucket.org/chromiumembedded/java-cef/src/304f3e3de03fb3aab5e8212c0f9c699503a55cb4/native/CefBrowser_N.cpp?at=master#CefBrowser_N.cpp-1393
https://bitbucket.org/chromiumembedded/java-cef/src/304f3e3de03fb3aab5e8212c0f9c699503a55cb4/native/jni_util.cpp?at=master#jni_util.cpp-126

https://stackoverflow.com/questions/32205446/getting-true-utf-8-characters-in-java-jni/32215302

**Comment by Hinaser** [comment] 2021-01-13 14:52
I've just submit a fixed version to JetBrains.
Once they approve it, you can update the plugin.
Thank you for reporting issue!

**Comment by Hinaser** [comment] 2021-01-14 12:50
https://plugins.jetbrains.com/plugin/14683-gfma
v0.0.4 is now available!
Closing.

**Closed by Hinaser** 2021-01-14 12:50 UTC
